# ------------------ BUILD ------------------
    ARG NODE_VERSION=22-alpine
    ARG PNPM_VERSION=10.11.0

    FROM node:${NODE_VERSION} AS builder
    ARG PNPM_VERSION

    RUN npm install -g pnpm@${PNPM_VERSION}

    WORKDIR /app

    COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
    RUN pnpm install --frozen-lockfile

    COPY . .
    RUN pnpm run build

    # ------------------ PRODUCTION ------------------
    FROM node:${NODE_VERSION} AS production
    ARG PNPM_VERSION

    RUN npm install -g pnpm@${PNPM_VERSION}

    WORKDIR /app

    COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
    RUN pnpm install --frozen-lockfile --prod

    COPY --from=builder /app/dist ./dist

    CMD ["node", "dist/main.js"]
